### PR TITLE
feat: update tonic to 0.11

### PR DESCRIPTION
**Pull request by sunng87**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Use tonic 0.11

## Checklist

- [ ]  I have written the necessary comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Comment by sunng87** [comment]
We will need to wait arrow 51 release and updated for greptimedb to merge this.

**Comment by sunng87** [comment]
Related https://github.com/GreptimeTeam/greptimedb/pull/3554

**Comment by tisonkun** [comment]
> We will need to wait arrow 51 release and updated for greptimedb to merge this.

What is the concrete issue/blocker here? Why should we wait for arrow upgrade to upgrade tonic?

**Comment by sunng87** [comment]
Just for a clean upgrade because arrow-flight has a dependency to tonic.

**Comment by tisonkun** [comment]
Resolved by https://github.com/GreptimeTeam/greptime-proto/pull/148.

**Pull request closed without merging**
