### PR TITLE
chore: change create database api

### PR DESCRIPTION
**Pull request by CookiePieWw**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

As described in https://github.com/GreptimeTeam/greptimedb/issues/3662, change `database_name` to `schema_name` for consistency.

## Checklist

- [ ]  I have written the necessary comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Review by shuiyisong — APPROVED** [review]
LGTM

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
Thank you!

**Comment by tisonkun** [comment]
@shuiyisong Although, is this patch a breaking change?

**Comment by shuiyisong** [comment]
> @shuiyisong Although, is this patch a breaking change?
> 
> If so, call it "chore" looks mismatched.

I think it's only used internally. So from a user's perspective I assume it is a not breaking change?

**Pull request merged**
