### PR TITLE
feat!: GreptimeRequest no longer has QueryRequest variant

### PR DESCRIPTION
**Pull request by tisonkun**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

This refers to https://github.com/GreptimeTeam/greptimedb/issues/3799.

## Checklist

- [ ]  I have written the necessary comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Review by MichaelScofield — APPROVED** [review]
This PR can be merged only after the corresponding issue is resolved.

**Comment by tisonkun** [comment]
@MichaelScofield Aha. Yes I can open a pr on the main repo and point to this commit.

**Review by fengjiachun — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
Closed for now.

**Pull request closed without merging**
