### PR TITLE
feat: add `IF EXISTS` for `DROP`

### PR DESCRIPTION
**Pull request by zuston**
For https://github.com/GreptimeTeam/greptimedb/issues/2794

I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

- Summarize your change

Add the `drop_if_exists` to match the mysql statement for `drop`

- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [ ]  I have written the necessary comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Comment by zuston** [comment]
PTAL @sunng87 @waynexia

**Comment by waynexia** [comment]
Please run `make` to generate language-specific code

**Comment by zuston** [comment]
> Please run `make` to generate language-specific code

Oh yes. I thought the generated code will be did by the bot.

**Review by waynexia — APPROVED** [review]

**Review by sunng87 — APPROVED** [review]
LGTM. 

Can you make a rebase to solve conflicts? Thank you!

**Comment by zuston** [comment]
> LGTM.
> 
> Can you make a rebase to solve conflicts? Thank you!

Sorry, it has some conflict and can't rebase. BTW, I don't have complete compile chain like golang and cmake in my mac.

**Comment by waynexia** [comment]
> > LGTM.
> > Can you make a rebase to solve conflicts? Thank you!
> 
> Sorry, it has some conflict and can't rebase. BTW, I don't have complete compile chain like golang and cmake in my mac.

Our makefile utilizes docker to generate code, only a docker env is required

**Comment by zuston** [comment]
> > > LGTM.
> > > Can you make a rebase to solve conflicts? Thank you!
> > 
> > 
> > Sorry, it has some conflict and can't rebase. BTW, I don't have complete compile chain like golang and cmake in my mac.
> 
> Our makefile utilizes docker to generate code, only a docker env is required

Yes, but my personal mac's docker client is connected to my company's internal docker server due to the limited disk space. And I found the golang dependency is still needed. 

image

**Comment by waynexia** [comment]
> > > > LGTM.
> > > > Can you make a rebase to solve conflicts? Thank you!
> > > 
> > > 
> > > Sorry, it has some conflict and can't rebase. BTW, I don't have complete compile chain like golang and cmake in my mac.
> > 
> > 
> > Our makefile utilizes docker to generate code, only a docker env is required
> 
> Yes, but my personal mac's docker client is connected to my company's internal docker server due to the limited disk space. And I found the golang dependency is still needed.
> 
> image

Whoops...

**Pull request merged**
