### PR TITLE
fix: modify cpp grpc CMakeLists.txt

### PR DESCRIPTION
**Pull request by Nateiru**
I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

fix some mistakes in CMakeLists.txt 

Please explain IN DETAIL what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [ ]  I have written the necessary comments.
- [ ]  I have added the necessary unit tests and integration tests.

### CODE REVIEW

**Review by WenyXu — APPROVED** [review]

**Comment by v0y4g3r** [comment]
Please resolve the conflicts.

**Comment by Nateiru** [comment]
> Please resolve the conflicts.

thanks, done!

**Review by v0y4g3r — COMMENTED** [review]
LGTM

**Review by v0y4g3r — APPROVED** [review]
LGTM

**Pull request merged**
